"""Object storage — durable blobs behind one small seam.

The filesystem on a hosted replica is a per-request scratchpad; anything that
must outlive the request (agent artifacts now, user uploads in Phase 2) goes
through :class:`ObjectStore`. Phase 1 ships the local-disk backend (dev and
single-node prod); an S3-compatible backend (Supabase Storage first) slots in
behind the same seam in Phase 3 — a config choice, not a code change.

Tenancy lives in the key: ``org/{org}/conv/{conv}/{uploads|outputs}/{file_id}/{name}``.
Every access path re-derives the prefix from the authenticated org, so a
leaked key string alone never crosses tenants.
"""

from __future__ import annotations

import os
import re
import shutil
import tempfile
from pathlib import Path
from typing import BinaryIO, Optional, Protocol

from .config import settings

_SAFE_SEGMENT = re.compile(r"[^A-Za-z0-9._-]+")


def safe_name(name: str) -> str:
    """A filename reduced to one safe path segment (no separators/traversal)."""
    base = os.path.basename(name.replace("\\", "/")).strip() or "file"
    cleaned = _SAFE_SEGMENT.sub("_", base).lstrip(".") or "file"
    return cleaned[:120]


def _segment(value: str) -> str:
    """One key segment, safe on every backend (personal org ids contain ':',
    which Windows paths reject — WinError 123). Uniqueness is not this
    function's job: every key embeds a fresh file_id uuid, and access control
    is the StoredFile row's org check, never the key string."""
    return _SAFE_SEGMENT.sub("_", value or "") or "unknown"


def artifact_key(
    organization_id: str, conversation_id: str, file_id: str, name: str
) -> str:
    return (
        f"org/{_segment(organization_id)}/conv/{_segment(conversation_id)}"
        f"/outputs/{_segment(file_id)}/{safe_name(name)}"
    )


def upload_key(
    organization_id: str, conversation_id: str, file_id: str, name: str
) -> str:
    return (
        f"org/{_segment(organization_id)}/conv/{_segment(conversation_id)}"
        f"/uploads/{_segment(file_id)}/{safe_name(name)}"
    )


class ObjectStore(Protocol):
    def put(self, key: str, data: BinaryIO, *, content_type: str) -> int:
        """Store the stream under key; returns bytes written."""
        ...

    def open(self, key: str) -> BinaryIO:
        """Streaming read. Raises FileNotFoundError when absent."""
        ...

    def delete(self, key: str) -> None: ...

    def url(self, key: str, *, expires_s: int = 300) -> Optional[str]:
        """Presigned GET when the backend supports it; None → stream via us."""
        ...


class LocalDiskObjectStore:
    """Dev/single-node backend: blobs on disk under one root, atomic writes."""

    def __init__(self, root: str):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        # Keys are generated by us, but stay paranoid: resolve and contain.
        target = (self.root / key).resolve()
        if not target.is_relative_to(self.root):
            raise ValueError(f"Storage key escapes the store root: {key!r}")
        return target

    def put(self, key: str, data: BinaryIO, *, content_type: str) -> int:
        target = self._path(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        # Atomic: write a temp file next to the target, then rename — a crash
        # mid-write can't leave a torn blob at the final key.
        fd, tmp = tempfile.mkstemp(dir=target.parent, suffix=".part")
        written = 0
        try:
            with os.fdopen(fd, "wb") as out:
                written = shutil.copyfileobj(data, out) or out.tell()
            os.replace(tmp, target)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
        return written

    def open(self, key: str) -> BinaryIO:
        return self._path(key).open("rb")

    def delete(self, key: str) -> None:
        try:
            self._path(key).unlink()
        except FileNotFoundError:
            pass

    def url(self, key: str, *, expires_s: int = 300) -> Optional[str]:
        return None


_STORE: Optional[ObjectStore] = None


def get_object_store() -> ObjectStore:
    global _STORE
    if _STORE is None:
        if settings.storage_backend != "local":
            raise RuntimeError(
                f"Unknown storage backend {settings.storage_backend!r} "
                "(only 'local' is implemented; 's3' is Phase 3)"
            )
        _STORE = LocalDiskObjectStore(settings.storage_dir)
    return _STORE
