"""Object storage — durable blobs behind one small seam.

The filesystem on a hosted replica is a per-request scratchpad; anything that
must outlive the request (agent artifacts now, user uploads in Phase 2) goes
through :class:`ObjectStore`. Phase 1 ships the local-disk backend (dev and
single-node prod); an S3-compatible backend (Supabase Storage first) slots in
behind the same seam in Phase 3 — a config choice, not a code change.

Tenancy lives in the key: ``org/{org}/conv/{conv}/{uploads|outputs}/{file_id}/{name}``.
Every access path re-derives the prefix from the authenticated org, so a
leaked key string alone never crosses tenants.
"""

from __future__ import annotations

import os
import re
import shutil
import tempfile
from pathlib import Path
from typing import BinaryIO, Optional, Protocol

from .config import settings

_SAFE_SEGMENT = re.compile(r"[^A-Za-z0-9._-]+")


def _filesystem_path(path: Path, *, windows: bool | None = None) -> str:
    """Return a syscall path that supports canonical long keys on Windows.

    The extended-length prefix changes only the local filesystem call. Logical
    object keys and their directory layout remain identical across backends.
    """
    raw = os.path.abspath(os.fspath(path))
    use_windows_paths = os.name == "nt" if windows is None else windows
    if not use_windows_paths or raw.startswith("\\\\?\\"):
        return raw
    if raw.startswith("\\\\"):
        return "\\\\?\\UNC\\" + raw[2:]
    return "\\\\?\\" + raw


def safe_name(name: str) -> str:
    """A filename reduced to one safe path segment (no separators/traversal)."""
    base = os.path.basename(name.replace("\\", "/")).strip() or "file"
    cleaned = _SAFE_SEGMENT.sub("_", base).lstrip(".") or "file"
    return cleaned[:120]


def _segment(value: str) -> str:
    """One key segment, safe on every backend (personal org ids contain ':',
    which Windows paths reject — WinError 123). Uniqueness is not this
    function's job: every key embeds a fresh file_id uuid, and access control
    is the StoredFile row's org check, never the key string."""
    return _SAFE_SEGMENT.sub("_", value or "") or "unknown"


def artifact_key(
    organization_id: str, conversation_id: str, file_id: str, name: str
) -> str:
    return (
        f"org/{_segment(organization_id)}/conv/{_segment(conversation_id)}"
        f"/outputs/{_segment(file_id)}/{safe_name(name)}"
    )


def upload_key(
    organization_id: str, conversation_id: str, file_id: str, name: str
) -> str:
    return (
        f"org/{_segment(organization_id)}/conv/{_segment(conversation_id)}"
        f"/uploads/{_segment(file_id)}/{safe_name(name)}"
    )


def event_cover_key(
    organization_id: str, event_id: str, file_id: str, name: str
) -> str:
    """Tenant-contained key for the current host-owned Event cover."""
    return (
        f"org/{_segment(organization_id)}/events/{_segment(event_id)}"
        f"/covers/{_segment(file_id)}/{safe_name(name)}"
    )


def event_setup_file_key(
    organization_id: str, draft_id: str, item_id: str, name: str
) -> str:
    """Tenant-contained blob staged before its Event exists."""
    return (
        f"org/{_segment(organization_id)}/event-drafts/{_segment(draft_id)}"
        f"/context/{_segment(item_id)}/{safe_name(name)}"
    )


def surface_bundle_key(
    organization_id: str,
    event_id: str,
    build_id: str,
    checksum: str,
) -> str:
    """Tenant-contained key for an immutable, untrusted Surface bundle."""
    return (
        f"org/{_segment(organization_id)}/events/{_segment(event_id)}"
        f"/surface-builds/{_segment(build_id)}/{_segment(checksum)}.zip"
    )


class ObjectStore(Protocol):
    def put(self, key: str, data: BinaryIO, *, content_type: str) -> int:
        """Store the stream under key; returns bytes written."""
        ...

    def open(self, key: str) -> BinaryIO:
        """Streaming read. Raises FileNotFoundError when absent."""
        ...

    def delete(self, key: str) -> None: ...

    def url(self, key: str, *, expires_s: int = 300) -> Optional[str]:
        """Presigned GET when the backend supports it; None → stream via us."""
        ...


class LocalDiskObjectStore:
    """Dev/single-node backend: blobs on disk under one root, atomic writes."""

    def __init__(self, root: str):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        # Keys are generated by us, but stay paranoid: resolve and contain.
        target = (self.root / key).resolve()
        if not target.is_relative_to(self.root):
            raise ValueError(f"Storage key escapes the store root: {key!r}")
        return target

    def put(self, key: str, data: BinaryIO, *, content_type: str) -> int:
        target = self._path(key)
        target_path = _filesystem_path(target)
        parent_path = _filesystem_path(target.parent)
        os.makedirs(parent_path, exist_ok=True)
        # Atomic: write a temp file next to the target, then rename — a crash
        # mid-write can't leave a torn blob at the final key.
        fd, tmp = tempfile.mkstemp(dir=parent_path, suffix=".part")
        written = 0
        try:
            with os.fdopen(fd, "wb") as out:
                shutil.copyfileobj(data, out)
                written = out.tell()
            os.replace(tmp, target_path)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
        return written

    def open(self, key: str) -> BinaryIO:
        return open(_filesystem_path(self._path(key)), "rb")

    def delete(self, key: str) -> None:
        try:
            os.unlink(_filesystem_path(self._path(key)))
        except FileNotFoundError:
            pass

    def url(self, key: str, *, expires_s: int = 300) -> Optional[str]:
        return None


class _ClosingBody:
    """Uniform context-manager wrapper over botocore's StreamingBody (its
    context-manager support varies by version; callers always use `with`)."""

    def __init__(self, body):
        self._body = body

    def read(self, n: int = -1) -> bytes:
        return self._body.read() if n is None or n < 0 else self._body.read(n)

    def close(self) -> None:
        self._body.close()

    def __enter__(self) -> "_ClosingBody":
        return self

    def __exit__(self, *exc) -> None:
        self.close()


class S3ObjectStore:
    """Any S3-compatible endpoint: AWS S3, Cloudflare R2, MinIO, Supabase
    Storage (S3 protocol). Presigned GETs let downloads bypass our backend
    entirely. `client` is injectable for tests; otherwise boto3 (optional
    dependency) builds one from settings."""

    def __init__(
        self,
        *,
        bucket: str,
        endpoint: str = "",
        access_key: str = "",
        secret_key: str = "",
        region: str = "us-east-1",
        client=None,
    ):
        if client is None:
            try:
                import boto3
            except ImportError as exc:
                raise RuntimeError(
                    "STORAGE_BACKEND=s3 requires boto3 (pip install boto3)"
                ) from exc
            client = boto3.client(
                "s3",
                endpoint_url=endpoint or None,
                aws_access_key_id=access_key or None,
                aws_secret_access_key=secret_key or None,
                region_name=region or None,
            )
        self.client = client
        self.bucket = bucket

    def put(self, key: str, data: BinaryIO, *, content_type: str) -> int:
        self.client.upload_fileobj(
            data, self.bucket, key, ExtraArgs={"ContentType": content_type}
        )
        try:
            return data.tell()
        except (OSError, ValueError):
            return 0

    def open(self, key: str) -> BinaryIO:
        try:
            body = self.client.get_object(Bucket=self.bucket, Key=key)["Body"]
        except Exception as exc:
            if _is_missing_key_error(exc):
                raise FileNotFoundError(key) from exc
            raise
        return _ClosingBody(body)  # type: ignore[return-value]

    def delete(self, key: str) -> None:
        self.client.delete_object(Bucket=self.bucket, Key=key)

    def url(self, key: str, *, expires_s: int = 300) -> Optional[str]:
        return self.client.generate_presigned_url(
            "get_object",
            Params={"Bucket": self.bucket, "Key": key},
            ExpiresIn=expires_s,
        )


def _is_missing_key_error(exc: Exception) -> bool:
    """True for botocore's NoSuchKey/404 ClientError shapes (duck-typed so an
    injected fake client can raise a plain exception named NoSuchKey)."""
    if type(exc).__name__ == "NoSuchKey":
        return True
    response = getattr(exc, "response", None)
    if isinstance(response, dict):
        code = str((response.get("Error") or {}).get("Code", ""))
        return code in {"NoSuchKey", "404", "NotFound"}
    return False


_STORE: Optional[ObjectStore] = None


def get_object_store() -> ObjectStore:
    global _STORE
    if _STORE is None:
        if settings.storage_backend == "local":
            _STORE = LocalDiskObjectStore(settings.storage_dir)
        elif settings.storage_backend == "s3":
            _STORE = S3ObjectStore(
                bucket=settings.storage_s3_bucket,
                endpoint=settings.storage_s3_endpoint,
                access_key=settings.storage_s3_access_key,
                secret_key=settings.storage_s3_secret_key,
                region=settings.storage_s3_region,
            )
        else:
            raise RuntimeError(
                f"Unknown storage backend {settings.storage_backend!r} "
                "(expected 'local' or 's3')"
            )
    return _STORE
