"""add_run_status

Revision ID: c718de95b2ea
Revises: 7893d0c163e7
Create Date: 2026-03-25 14:21:06.343048

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c718de95b2ea"
down_revision: Union[str, Sequence[str], None] = "7893d0c163e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs",
        sa.Column(
            "status",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="completed",
        ),
    )
    # Remove the server default after backfilling existing rows
    with op.batch_alter_table("runs") as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
            server_default=None,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs") as batch_op:
        batch_op.drop_column("status")
    # ### end Alembic commands ###
